/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hotheart_starcraft_map_TileLib */

#ifndef _Included_hotheart_starcraft_map_TileLib
#define _Included_hotheart_starcraft_map_TileLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hotheart_starcraft_map_TileLib
 * Method:    init_native
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_hotheart_starcraft_map_TileLib_init_1native
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     hotheart_starcraft_map_TileLib
 * Method:    draw_native
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_hotheart_starcraft_map_TileLib_draw_1native
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
